{{- with .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nut-exporter.fullname" $ }}{{ $.Values.secret.name }}
type: Opaque
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ b64enc $val }}
  {{- end }}
immutable: true          
{{- end }}
